global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
  - job_name: "identity-service"
    static_configs:
      - targets: ["identity-service:8000"]
  - job_name: "wallet-service"
    static_configs:
      - targets: ["wallet-service:8000"]
  - job_name: "payments-service"
    static_configs:
      - targets: ["payments-service:8000"]
  - job_name: "risk-service"
    static_configs:
      - targets: ["risk-service:8000"]
